### ISSUE TITLE
System Missing method exception

### ISSUE THREAD

**Issue by joshthebossxl** [JavidPack/TerraCustom#18]
Hi there again, I am getting this issue whenever I launch the actual application,  I have followed the install intructions in the readme.txt and I am still having issues trying to get this to work 
![image](https://user-images.githubusercontent.com/46633032/54086163-b548ef00-433e-11e9-92c8-dfa3626afb3b.png)

![image](https://user-images.githubusercontent.com/46633032/54086167-cdb90980-433e-11e9-8014-da24b9a0803b.png)

**Comment by JavidPack** [comment]
You have the 64 bit installation of tmodloader installed, I can't really anticipate that, they are incompatible.
