### ISSUE TITLE
How to run compiled TerraCustom in linux?

### ISSUE THREAD

**Issue by Varble12** [JavidPack/TerraCustom#37]
I edited the terracustom source and want to run it in linux. I already ran LinuxRelease in Visual Studio and TerraCustom launched without any issue in Windows. Now i have these files in the LinuxRelease folder:
![Untitled](https://user-images.githubusercontent.com/77456320/105479476-cab23280-5ca4-11eb-9de0-cd566b8fc10d.png)
Now my question is: What do I do with them? How can I use them to run the TerraCustom edit in linux?

**Comment by JavidPack** [comment]
Easiest way would be to download the latest TerraCustom release, install it as instructed, then take the Terraria.exe you have there in this folder and use it to replace TerraCustom.exe in the install folder of TerraCustom, and then run TerraCustom as mentioned in the readme.

**Comment by Varble12** [comment]
> Easiest way would be to download the latest TerraCustom release, install it as instructed, then take the Terraria.exe you have there in this folder and use it to replace TerraCustom.exe in the install folder of TerraCustom, and then run TerraCustom as mentioned in the readme.

thank you, it works!
Closing this issue
