### ISSUE TITLE
Double pyramids

### ISSUE THREAD

**Issue by zkreeg** [JavidPack/TerraCustom#6]
Double pyramid staircase leading down from pyramid treasure room. Single and multiple pyramids all exhibit this.

In TerraCustom 0.5.1 I have tried default settings and previously saved setting with Tmod 0.10.0.1 for Terraria 1.3.5.2. It also happens with Vanilla Terraria 1.3.5.3. 

The img was taken of TEdit v3.10

![capture](https://user-images.githubusercontent.com/29342528/27053915-f2981702-4f73-11e7-9782-b812f57a7c4c.PNG)

**Comment by JavidPack** [comment]
Are you sure you are on 0.5.1? Does it say that in the bottom left corner?

I tested this many, many times on the latest release and had no problems.

**Comment by zkreeg** [comment]
My mistake. I was using the wrong executable.
